version: '{{ params.version }}'

{% if params.networks | default({})
| dict2items | default([]) | list | length > 0 
%}networks: {{ params.networks | to_json }}
{% endif %}
      
services:

  {% for item in params.services | default({}) | dict2items 
  | sort(attribute='key') | map(attribute='key') | list 
  %}
  {% set item_params = params.services[item] %}  
  {% if item_params.when | default('true') | bool %}
  {% set name_dest = item_params.name_dest | default(item) %}

  {{ name_dest }}:
    hostname: "{{ name_dest }}"
    container_name: "${CTX_NAME}-{{ name_dest }}"
    build: 
      context: ./
      dockerfile: "${POD_ENV_DIR}/{{ name_dest }}/Dockerfile"
      args:
        IMAGE: "{{ item_params.image }}"
        VERSION: "{{ item_params.version }}"
        ENV_DIR: "${POD_ENV_DIR}/{{ name_dest }}"
        {% if item_params.args | default([]) | list | length > 0 
        %}{% for subitem in item_params.args | list 
        %}{{ subitem.name }}: {{ subitem.value }}
        {% endfor %}
        {% endif %}        
    restart: "{{ item_params.restart | default('unless-stopped') }}"

    {% if item_params.depends_on | default([]) | list | length > 0 %}depends_on:
    {% for subitem in item_params.depends_on | list %}- "{{ subitem }}"
    {% endfor %}
    {% endif %}

    {% if item_params.volumes | default([]) | list | length > 0 %}volumes:
    {% for subitem in item_params.volumes | list %}- "{{ subitem }}"
    {% endfor %}
    {% endif %}

    {% if item_params.networks | default([]) | list | length > 0 %}networks:
    {% for subitem in item_params.networks | list %}- "{{ subitem }}"
    {% endfor %}
    {% endif %}

    {% if item_params.ports | default([]) | list | length > 0 %}ports:
    {% for subitem in item_params.ports | list %}- "{{ subitem }}"
    {% endfor %}
    {% endif %}

    {% if item_params.environment | default({})
    | dict2items | default([]) | list | length > 0 
    %}environment: {{ item_params.environment | to_json }}
    {% endif %}

    {% if item_params.ulimits | default({})
    | dict2items | default([]) | list | length > 0 
    %}ulimits: {{ item_params.ulimits | to_json }}
    {% endif %}

    {% if (item_params.mem_limit | default('')) != '' 
    %}mem_limit: "{{ item_params.mem_limit }}"
    {% endif %}

    {% if (item_params.working_dir | default('')) != '' 
    %}working_dir: "{{ item_params.working_dir }}"
    {% endif %}

    {% if (item_params.command | default('')) != '' 
    %}command: "{{ item_params.command }}"
    {% endif %}

    {% if (item_params.logging | default('')) != '' 
    %}logging: {{ params.logging[item_params.logging] | to_json }}
    {% endif %}

  ### {{ name_dest }}{{ (name_dest != item) | ternary(' (' + item + ')', '') }} - end ###
  {% endif %}
  {% endfor %}
