templates:

- dir_base: "main/compose"
  src: "docker-compose.yml"
  dest: "docker-compose.yml"
  root: true
  params: {{ params.compose | to_json }}

- dir_base: "main/compose"
  src: ".env"
  dest: ".env"
  root: true
  params: 
    ctx_name: "{{ params.env.base_params.pod_id }}"
    pod_repo: "{{ params.env.base_params.pod.repo }}"
    pod_repo_version: "{{ params.env.base_params.pod.repo_version }}"
    git_commit: "{{ params.env.base_params.git_commit }}"
    pod_env_dir: "{{ params.env.base_params.pod_env_dir }}"
    data_dir: "{{ params.env.base_params.data_dir }}"
    env_params: "{{ params.env.env_params }}"
    env_encoded_list: {{ params.env.env_encoded_list | to_json }}
