templates:

- src: "main/compose/docker-compose.yml"
  dest: "docker-compose.yml"
  root: true
  params: {{ params.compose | to_json }}

- src: "main/compose/.env"
  dest: ".env"
  root: true
  params: 
    ctx_name: "{{ params.env.base_params.pod_id }}"
    pod_repo: "{{ params.env.base_params.repo.src }}"
    pod_repo_version: "{{ params.env.base_params.repo.version }}"
    git_commit: "{{ params.env.base_params.git_commit }}"
    pod_env_dir: "{{ params.env.base_params.pod_env_dir }}"
    data_dir: "{{ params.env.base_params.data_dir }}"
    env_list: {{ params.env.env_list | to_json }}
    env_encoded_list: {{ params.env.env_encoded_list | to_json }}
