version: '3.4'

networks:
  # elk:
  #   driver: bridge
  # fluentd:
  #   driver: bridge
  internet:
    driver: bridge
  # no-internet:
  #   driver: bridge
  #   internal: true
    
volumes:
  db_data:

  # fluentd:
    
  # mongo:

x-logging: 
  main: &mainlog
    options:
      max-size: 50m
    
  fluentd: &fluentd
    driver: fluentd
    options:
      fluentd-address: "localhost:24224"
      tag: "{{.Name}}"

  gelf: &gelf
    driver: gelf
    options:
      gelf-address: udp://localhost:12201
      tag: "staging"

services:
  # stats:
  #   build: ./stats
  #   restart: on-failure
  #   volumes:
  #    - /etc/localtime:/etc/localtime:ro
  #    - /var/run/docker.sock:/var/run/docker.sock
  #   logging: &gelf
  #     driver: gelf
  #     options:
  #       gelf-address: udp://localhost:12201
  #       tag: "staging"

  nginx:
    build: ./nginx
    restart: on-failure
    volumes:
     - /etc/localtime:/etc/localtime:ro
    depends_on:
     - wordpress
     - phpmyadmin
     - main-server
     - websocket
     - wildfly
     - gradle
    ports:
     - "80:80"
     - "8000:8000"
     - "9000:9000"
     - "9001:9001"
     - "9002:9002"
    networks:
      - internet
    logging: *mainlog

  wordpress:
    image: wordpress:latest
    restart: on-failure
    volumes:
     - /etc/localtime:/etc/localtime:ro
    depends_on:
     - mysql
    environment:
     - WORDPRESS_DB_HOST=mysql:3306
     - WORDPRESS_DB_USER=wordpress
     - WORDPRESS_DB_PASSWORD=123456
    networks:
      - internet
    logging: *mainlog

  main-server:
    build: ./server
    restart: on-failure
    volumes:
     - /etc/localtime:/etc/localtime:ro
    environment:
     - NAME=Server
    networks:
      - internet
    logging: *mainlog

  websocket:
    build: ./websocket
    restart: on-failure
    volumes:
     - /etc/localtime:/etc/localtime:ro
    ports:
     - "2053:3000"
    depends_on:
     - redis
    networks:
      - internet
    logging: *mainlog

  redis:
    image: redis:alpine
    restart: on-failure
    volumes:
     - /etc/localtime:/etc/localtime:ro
    expose:
     - "6379"
    networks:
      - internet
    logging: *mainlog

#   adminer:
#     image: adminer
#     restart: on-failure
#     volumes:
#      - /etc/localtime:/etc/localtime:ro
#     ports:
#      - 9080:8080
#     depends_on:
#      - mysql:db
#     networks:
#       - internet
#     logging: *mainlog

#   mantisbt:
#     image: lucasbasquerotto/mantisbt
#     restart: on-failure
#     volumes:
#      - /etc/localtime:/etc/localtime:ro
#     ports:
#      - 8082:80
#     depends_on:
#      - mysql:db
#     networks:
#       - internet
#     logging: *gelf

  gradle:
    image: lucasbasquerotto/gradle-demo-webapp
    restart: on-failure
    volumes:
     - /etc/localtime:/etc/localtime:ro
    networks:
      - internet
    logging: *mainlog

  wildfly:
    build:
      context: wildfly/
      args:
        WILDFLY_VERSION: $WILDFLY_VERSION
    restart: on-failure
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "9990:9990"
    networks:
      - internet
    logging: *mainlog

#   logstash:
#     build:
#       context: logstash/
#       args:
#         ELK_VERSION: $ELK_VERSION
#     restart: on-failure
#     volumes:
#      - /etc/localtime:/etc/localtime:ro
#     environment:
#       - "LS_JAVA_OPTS=-Xmx256m -Xms256m"
#     ports:
#       - "12201:12201/udp"
#       - "5044:5044"
#     networks:
#       - elk
#     depends_on:
#       - elasticsearch
#     logging: *fluentd

#   elasticsearch:
#     build:
#       context: elasticsearch/
#       args:
#         ELK_VERSION: $ELK_VERSION
#     restart: on-failure
#     volumes:
#      - /etc/localtime:/etc/localtime:ro
#     ports:
#       - "9200:9200"
#       - "9300:9300"
#     environment:
#       - "ES_JAVA_OPTS=-Xmx256m -Xms256m"
#     networks:
#       - elk 
#     logging: *fluentd     

#   kibana:
#     build:
#       context: kibana/
#       args:
#         ELK_VERSION: $ELK_VERSION
#     restart: on-failure
#     volumes:
#      - /etc/localtime:/etc/localtime:ro
#     depends_on:
#       - elasticsearch
#     ports:
#       - "5601:5601"
#     networks:
#       - elk
#     logging: *fluentd

  # fluentd:
  #   build:
  #     context: fluentd/
  #   restart: on-failure
  #   volumes:
  #    - /etc/localtime:/etc/localtime:ro
  #    - fluentd:/fluentd/log 
  #   ports:
  #     - "24224:24224"
  #   networks:
  #     - fluentd
  #   logging: &logging
  #     options:
  #       max-size: 50m
      
  # mongo:
  #   build:
  #     context: mongo/
  #   restart: on-failure
  #   volumes:
  #    - /etc/localtime:/etc/localtime:ro
  #    - mongo:/data/db
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: example
  #     MONGO_INITDB_DATABASE: log
  #     # MONGODB_APPLICATION_DATABASE: fluentd
  #     # MONGODB_APPLICATION_USER: root
  #     # MONGODB_APPLICATION_PASS: example
  #     # MONGODB_APPLICATION_USER: fluent
  #     # MONGODB_APPLICATION_PASS: fluent123
  #   networks:
  #     - fluentd
  #   logging: *logging

  # mongo-express:
  #   image: mongo-express
  #   restart: on-failure
  #   volumes:
  #    - /etc/localtime:/etc/localtime:ro
  #   ports:
  #     - 8181:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #   networks:
  #     - fluentd
  #   logging: *logging

  # fail2ban:
  #   image: crazymax/fail2ban:latest
  #   restart: on-failure
  #   network_mode: "host"
  #   cap_add:
  #     - NET_ADMIN
  #     - NET_RAW
  #   volumes:
  #     - "./data:/data"
  #     - "/var/log:/var/log:ro"
  #   logging: &mainlog
  #     options:
  #       max-size: 50m

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: on-failure
    volumes:
     - /etc/localtime:/etc/localtime:ro
    environment:
     - PMA_HOST=mysql
     - PMA_PORT=3306
    networks:
      - internet
    logging: *mainlog

  mysql:
    image: mysql:5.7
    restart: on-failure
    volumes:
     - /etc/localtime:/etc/localtime:ro
     - db_data:/var/lib/mysql
    environment:
     - MYSQL_ROOT_PASSWORD=pass01
     - MYSQL_USER=wordpress
     - MYSQL_PASSWORD=123456
     - MYSQL_DATABASE=wordpress
    ports: 
     - 3306:3306
    networks:
      - internet
    logging: *mainlog