version: '3.3'

services:
  nginx:
    build: ./nginx
    links:
      - server-john
      - server-paul
      - server-george
      - server-ringo
    ports:
    - "3000:80"

  server-john:
    build: ./server
    links:
      - redis
    expose:
      - "3000"
    environment:
      - NAME=John

  server-paul:
    build: ./server
    links:
      - redis
    expose:
      - "3000"
    environment:
      - NAME=Paul

  server-george:
    build: ./server
    links:
      - redis
    expose:
      - "3000"
    environment:
      - NAME=George

  server-ringo:
    build: ./server
    links:
      - redis
    expose:
      - "3000"
    environment:
      - NAME=Ringo

  redis:
    container_name: redis
    image: redis:alpine
    expose:
      - "6379"

  mysql:
      image: mysql:5.7
      restart: always
      environment:
      - MYSQL_ROOT_PASSWORD=pass01
      - MYSQL_USER=viewer
      - MYSQL_PASSWORD=pass02
      ports: 
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    links:
      - mysql:db

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      restart: always
      environment:
      - PMA_HOST=db 
      - PMA_PORT=3306
      #- PMA_ARBITRARY=1
      ports:
      - 8081:80
      links:
      - mysql:db

  mantisbt:
    build: ./mantisbt
    restart: always
    ports:
      - 8082:80
    links:
      - mysql:db
      