version: '3.3'

services:
  nginx:
    build: ./nginx
    links:
      - server
      - websocket
    ports:
      - "80:80"
      - "7000:7000"

  server:
    build: ./server
    ports:
      - "8000:80"
    environment:
      - NAME=Server

  websocket:
    build: ./websocket
    ports:
      - "3000:3000"
    links:
      - redis

  redis:
    container_name: redis
    image: redis:alpine
    expose:
      - "6379"

  mysql:
    image: mysql:5.7
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pass01
      - MYSQL_USER=viewer
      - MYSQL_PASSWORD=pass02
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    ports: 
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    links:
      - mysql:db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      - PMA_HOST=db 
      - PMA_PORT=3306
      #- PMA_ARBITRARY=1
    ports:
      - 8081:80
    links:
      - mysql:db

  mantisbt:
    build: ./mantisbt
    restart: always
    ports:
      - 8082:80
    links:
      - mysql:db

  wordpress:
    image: wordpress:latest
    depends_on:
      - mysql
    links:
      - mysql:db
    restart: always
    ports:
      - "8083:80"
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress

volumes:
    db_data: