version: '3.3'

services:
  nginx:
    build: ./nginx
    restart: always
    links:
      - main-server
      - websocket
    ports:
      - "80:9000"
      - "3999:7000"

  main-server:
    build: ./server
    restart: always
    ports:
      - "8000:8099"
    environment:
      - NAME=Server

  websocket:
    build: ./websocket
    restart: always
    ports:
      - "3111:3000"
    links:
      - redis

  redis:
    image: redis:alpine
    restart: always
    expose:
      - "6379"

  mysql:
    image: mysql:5.7
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pass01
      - MYSQL_USER=viewer
      - MYSQL_PASSWORD=pass02
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    ports: 
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    links:
      - mysql:db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      - PMA_HOST=db 
      - PMA_PORT=3306
      #- PMA_ARBITRARY=1
    ports:
      - 8081:80
    links:
      - mysql:db

  mantisbt:
    image: lucasbasquerotto/mantisbt
    restart: always
    ports:
      - 8082:80
    links:
      - mysql:db

  wordpress:
    image: wordpress:latest
    restart: always
    depends_on:
      - mysql
    links:
      - mysql:db
    ports:
      - "8083:80"
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress

volumes:
  db_data:

  portainer_data:

  mariadb_data:
    driver: local
  magento_data:
    driver: local
