version: '3.3'

services:
  stats:
    build: ./stats
    restart: on-failure
    volumes:
     - /etc/localtime:/etc/localtime:ro
     - /var/run/docker.sock:/var/run/docker.sock
    logging: &logging
      options:
        max-size: 50m

  nginx:
    build: ./nginx
    restart: on-failure
    volumes:
     - /etc/localtime:/etc/localtime:ro
    links:
     - main-server
     - websocket
    ports:
     - "80:9000"
     - "3999:7000"
    logging: *logging

  main-server:
    build: ./server
    restart: on-failure
    volumes:
     - /etc/localtime:/etc/localtime:ro
    ports:
     - "8000:8099"
    environment:
     - NAME=Server
    logging: *logging

  websocket:
    build: ./websocket
    restart: on-failure
    volumes:
     - /etc/localtime:/etc/localtime:ro
    ports:
     - "3111:3000"
    links:
     - redis
    logging: *logging

  redis:
    image: redis:alpine
    restart: on-failure
    volumes:
     - /etc/localtime:/etc/localtime:ro
    expose:
     - "6379"
    logging: *logging

  mysql:
    image: mysql:5.7
    restart: on-failure
    volumes:
     - /etc/localtime:/etc/localtime:ro
     - db_data:/var/lib/mysql
    environment:
     - MYSQL_ROOT_PASSWORD=pass01
     - MYSQL_USER=viewer
     - MYSQL_PASSWORD=pass02
     - MYSQL_DATABASE=wordpress
     - MYSQL_USER=wordpress
     - MYSQL_PASSWORD=wordpress
    ports: 
     - 3306:3306
    logging: *logging

  adminer:
    image: adminer
    restart: on-failure
    volumes:
     - /etc/localtime:/etc/localtime:ro
    ports:
     - 8080:8080
    links:
     - mysql:db
    logging: *logging

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: on-failure
    volumes:
     - /etc/localtime:/etc/localtime:ro
    environment:
     - PMA_HOST=db 
     - PMA_PORT=3306
    ports:
     - 8081:80
    links:
     - mysql:db
    logging: *logging

  mantisbt:
    image: lucasbasquerotto/mantisbt
    restart: on-failure
    volumes:
     - /etc/localtime:/etc/localtime:ro
    ports:
     - 8082:80
    links:
     - mysql:db
    logging: *logging

  wordpress:
    image: wordpress:latest
    restart: on-failure
    volumes:
     - /etc/localtime:/etc/localtime:ro
    depends_on:
     - mysql
    links:
     - mysql:db
    ports:
     - "8083:80"
    environment:
     - WORDPRESS_DB_HOST=db:3306
     - WORDPRESS_DB_USER=wordpress
     - WORDPRESS_DB_PASSWORD=wordpress
    logging: *logging

  #filebeat:
  #  build: ./filebeat
  #  restart: on-failure
  #  volumes:
  #   - /etc/localtime:/etc/localtime:ro
  #  logging: *logging

  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    ports:
      - "5000:5000"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch
    logging: *logging

  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk 
    logging: *logging     

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch
    logging: *logging
      
networks:
  elk:
    driver: bridge
    
volumes:
  db_data: