volumes:
- { path: "/data/{{ params.project }}/main/uploads", mode: "0777" }

templates:

- src: ".env"
  root: true
  params: 
    docker_repo: "{{ params_aux.docker_repo }}"
    docker_repo_version: "{{ params_aux.docker_repo_version }}"
    git_commit: "{{ params_aux.git_commit }}"
    project: "{{ params.project }}"
    perl_version: "5.26.3-slim"
    nginx_version: "1.14.2-alpine"
    main_image: "wordpress"
    main_version: "5.2.2"
    pma_version: "4.8.5"
    mysql_image: "mysql"
    mysql_version: "8.0.16"
    mysql_root_password: "{{ params.mysql.root_password }}"
    db_host: "db"
    db_port: 3306
    db_name: "wordpress"
    db_user: "wp_user"
    db_password: "{{ params.db_password }}"
    env_vars: "{{ params }}"

- src: "compose/docker-compose.dev.yml"
  root: true  
  dest: "docker-compose.yml"

#############
### Nginx ###
#############

- src: "nginx/nginx.conf"
  params:
    worker_processes: 1
    worker_connections: 512
    includes:
    - "includes/log.conf"
    - "includes/limit_req_zone.conf"
    - "includes/limit_conn_zone.conf"
    - "includes/limit_conn_zone_file_upload.conf"
    - "includes/proxy_cache.conf"
    - "includes/timeouts.conf"
    servers:
    - name: "www"
      host: "www.{{ params.domain }}"
      port: "{{ params.ssl | ternary('443', '80') }}"
      ssl: "{{ params.ssl }}"
      redirect:
        protocol: "{{ params.ssl | ternary('https', 'http') }}"
        host: "{{ params.domain }}"
        port: "{{ params.ssl | ternary('443', '80') }}"
    - name: "main"
      host: "{{ params.domain }}"
      port: "{{ params.ssl | ternary('443', '80') }}"
      ssl: "{{ params.ssl }}"
      upstream:
        protocol: "http"
        port: "80"
      locations:
      - path: "/wp-admin/"
        includes:
        - "includes/file_upload.conf"
        - "includes/file_upload_ratelimit.conf"
      - path: "/"
    - name: "db_admin"
      host: "{{ params.db_admin.domain }}"
      port: "{{ params.db_admin.port }}"
      ssl: "{{ params.db_admin.ssl }}"
      upstream:
        protocol: "http"
        port: "80"
      locations:
      - path: "/"

- src: "nginx/includes/log.conf"
  params: 
    format: >-
      $remote_addr $sent_http_x_user_id $upstream_response_time $status
      $remote_user [$time_local] "$host" "$request"
      $body_bytes_sent "$http_referer" "$http_user_agent" $request_time

- src: "nginx/includes/limit_req_zone.conf"
  params: 
    zone: "mainlimit"
    size: "10m"
    rate: "2r/s"

- src: "nginx/includes/limit_conn_zone.conf"
  params:
    zone: "connlimit"
    size: "10m"

- src: "nginx/includes/limit_conn_zone.conf"
  dest: "nginx/includes/limit_conn_zone_file_upload.conf"
  params: 
    zone: "uploadconnlimit"
    size: "10m"

- src: "nginx/includes/proxy_cache.conf"
  params:
    proxy_cache_path: "/var/cache/nginx"
    levels: "1:2"
    keys_zone: "web_cache"
    size: "20m"
    max_size: "200m"
    inactive: "30m"

- src: "nginx/includes/timeouts.conf"
  params:
    proxy_connect_timeout: "30"
    proxy_send_timeout: "60"
    proxy_read_timeout: "60"
    send_timeout: "60"
    client_body_timeout: "5s"
    client_header_timeout: "5s"

- src: "nginx/includes/file_upload.conf"
  params: 
    proxy_read_timeout: "240"
    client_max_body_size: "10M"

- src: "nginx/includes/ratelimit.conf"
  dest: "nginx/includes/file_upload_ratelimit.conf"
  params:
    limit_req:
      zone: "mainlimit"
      burst: 6
      nodelay: true
    limit_conn:
      name: "uploadconnlimit"
      value: 5

#################
### Wordpress ###
#################

- src: "wordpress/wp-config.php"
  params: 
    db_password: "{{ params.db_password }}"
    db_charset: "utf8mb4"
    db_collate: ""
    home: "{{ params.ssl | ternary('https', 'http') }}://{{ params.domain }}"
    siteurl: "{{ params.ssl | ternary('https', 'http') }}://{{ params.domain }}"
    auth_key: "{{ params.wp.auth_key }}"
    secure_auth_key: "{{ params.wp.secure_auth_key }}"
    logged_in_key: "{{ params.wp.logged_in_key }}"
    nonce_key: "{{ params.wp.nonce_key }}"
    auth_salt: "{{ params.wp.auth_salt }}"
    secure_auth_salt: "{{ params.wp.secure_auth_salt }}"
    logged_in_salt: "{{ params.wp.logged_in_salt }}"
    nonce_salt: "{{ params.wp.nonce_salt }}"
    table_prefix: "wp_"
    wplang: "en_US"
    wp_debug: "{{ params.wp_debug | default(false) | lower }}"

##################
### PHPMyAdmin ###
##################

- src: "phpmyadmin/config.user.inc.php"
  params:
    login_cookie_validity: 36000

#############
### MySQL ###
#############

- src: "mysql/mysqld.cnf"
  params:
    bind_address: "0.0.0.0"
    default_authentication_plugin: "mysql_native_password"
    collation_server: "utf8mb4_unicode_ci"
    character_set_server: "utf8mb4"
    slow_query_log: "1"
    slow_query_log_file: "var/log/mysql/mysql-slow.log"
    long_query_time: "3"
    log_error: "/var/log/mysql/error.log"
