params:
- name: "main.app"
  params:
    volumes:
      data_dir: "{{ params_aux.data_dir_inside }}"
    wordpress:
      image: "{{ params.wordpress.image }}"
      version: "{{ params.wordpress.version }}"
      env: "{{ params.wordpress.env }}"
      domain: "{{ params.wordpress.domain }}"
      db_password: "{{ params.wordpress.db_password }}"
      ssl: "{{ params.wordpress.ssl }}"
      config:
        auth_key: "{{ params.wordpress.config.auth_key }}"
        secure_auth_key: "{{ params.wordpress.config.secure_auth_key }}"
        logged_in_key: "{{ params.wordpress.config.logged_in_key }}"
        nonce_key: "{{ params.wordpress.config.nonce_key }}"
        auth_salt: "{{ params.wordpress.config.auth_salt }}"
        secure_auth_salt: "{{ params.wordpress.config.secure_auth_salt }}"
        logged_in_salt: "{{ params.wordpress.config.logged_in_salt }}"
        nonce_salt: "{{ params.wordpress.config.nonce_salt }}"
    phpmyadmin:
      domain: "{{ params.phpmyadmin.domain }}"
      port: "{{ params.phpmyadmin.port }}"
      ssl: "{{ params.phpmyadmin.ssl }}"
    mysql: 
      image: "{{ params.mysql.image }}"
      version: "{{ params.mysql.version }}"
      root_password: "{{ params.mysql.root_password }}"
    toolbox:
      image: "{{ params.toolbox.image }}"
      version: "{{ params.toolbox.version }}"
      s3cmd:
        access_key: "{{ params.toolbox.s3cmd.access_key }}"
        secret_key: "{{ params.toolbox.s3cmd.secret_key }}"
        host_base: "{{ params.toolbox.s3cmd.host_base }}"

- name: "compose.local"
  params: 
    env:  
      db_password: "{{ params.wordpress.db_password }}"
      mysql_root_password: "{{ params.mysql.root_password }}"

      ctx_name: "{{ params_aux.ctx_name }}"
      pod_repo: "{{ params_aux.pod.repo }}"
      pod_repo_version: "{{ params_aux.pod.repo_version }}"
      git_commit: "{{ params_aux.git_commit }}"
      data_dir: "{{ params_aux.data_dir }}"
      wordpress_dev_repo_dir: "{{ params_aux.app.wordpress.dir_rel }}"

      mysql_image: "{{ params.mysql.image }}"
      mysql_version: "{{ params.mysql.version }}"
      db_host: "{{ params.mysql.db_host | default('mysql', true) }}"
      db_port: "{{ params.mysql.db_port | default('3306', true) }}"
      db_name: "{{ params.mysql.db_name | default('wordpress', true) }}"
      db_user: "{{ params.mysql.db_user | default('wp_user', true) }}"
      mysql_cmd: "{{ params.mysql.cmd | default('') }}"
    composer:
      image: "{{ params.composer.image }}"
      version: "{{ params.composer.version }}"
    run:
      repo_name: "{{ params_aux.repo_name }}"
      setup_url: "{{ params.setup.url }}"
      setup_title: "{{ params.setup.title }}"
      setup_admin_user: "{{ params.setup.admin_user }}"
      setup_admin_password: "{{ params.setup.admin_password }}"
      setup_admin_email: "{{ params.setup.admin_email }}"
      setup_local_db_file: "{{ params.run.local_db_file | default('') }}"
      setup_remote_db_file: "{{ params.run.remote_db_file | default('') }}"
      setup_local_uploads_zip_file: "{{ params.run.local_uploads_zip_file | default('') }}"
      setup_remote_uploads_zip_file: "{{ params.run.remote_uploads_zip_file | default('') }}"
      setup_local_seed_data: "{{ params.run.local_seed_data | default('') }}"
      setup_remote_seed_data: "{{ params.run.remote_seed_data | default('') }}"
      s3cmd_access_key: "{{ params.toolbox.s3cmd.access_key }}"
      s3cmd_secret_key: "{{ params.toolbox.s3cmd.secret_key }}"
      s3cmd_host_base: "{{ params.toolbox.s3cmd.host_base }}"
    env_run:
      wordpress_dev_repo_dir: "{{ params_aux.app.wordpress.dir_rel }}"