version: '3.4'

networks:
  internet:
    driver: bridge
  local:
    driver: bridge
    internal: true
    
x-logging: 
  main: &mainlog
    options:
      max-size: 50m
      
services:
  nginx:
    hostname: nginx
    build: 
      context: ./
      dockerfile: env/nginx/Dockerfile
    restart: on-failure
    depends_on:
    - wordpress
    - phpmyadmin
    ports:
    - "80:80"
    - "8080:8080"
    networks:
    - internet
    - local
    logging: *mainlog

  wordpress:
    hostname: wordpress
    build: 
      context: ./
      dockerfile: env/wordpress/Dockerfile
    restart: on-failure
    depends_on:
    - mysql
    environment:
    - DB_HOST=$DB_HOST:$DB_PORT
    - DB_NAME=$DB_NAME
    - DB_USER=$DB_USER 
    volumes:
    - $WP_REPO_DIR:/var/www/html
    - $DATA_DIR/wordpress/uploads:/var/www/html/web/app/uploads
    networks:
    - internet
    - local
    logging: *mainlog

  phpmyadmin:
    hostname: phpmyadmin
    build: 
      context: ./
      dockerfile: env/phpmyadmin/Dockerfile
    restart: on-failure
    depends_on:
    - mysql
    environment:
    - PMA_HOST=$DB_HOST
    - PMA_PORT=$DB_PORT
    networks:
    - local
    logging: *mainlog

  mysql:
    hostname: mysql
    build: 
      context: ./
      dockerfile: env/mysql/Dockerfile
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
    volumes:
    - $DATA_DIR/mysql:/var/lib/mysql
    - $DATA_DIR/tmp/mysql:/tmp/main
    networks:
    - local
    logging: *mainlog
    command: $MYSQL_CMD

  composer:
    hostname: composer
    build: 
      context: ./
      dockerfile: env/composer/Dockerfile
    restart: on-failure
    working_dir: /var/www/html
    volumes:
    - $WP_REPO_DIR:/var/www/html
    networks:
    - internet
    - local
    logging: *mainlog
    command: tail -f /dev/null
