volumes:
- { path: "/data/mysql", mode: "0700" }
- { path: "/data/wordpress/uploads", mode: "0777" }

templates:

#############
### Nginx ###
#############

- src: "nginx/Dockerfile"
  params:
    nginx_image: "nginx"
    nginx_version: "1.14.2-alpine"

- src: "nginx/nginx.conf"
  params:
    worker_processes: 1
    worker_connections: 512
    includes:
    - "includes/log.conf"
    - "includes/limit_req_zone.conf"
    - "includes/limit_conn_zone.conf"
    - "includes/limit_conn_zone_file_upload.conf"
    - "includes/proxy_cache.conf"
    - "includes/timeouts.conf"
    servers:
    - name: "www"
      host: "www.{{ params.wordpress.domain }}"
      port: "{{ params.wordpress.ssl | ternary('443', '80') }}"
      ssl: "{{ params.wordpress.ssl }}"
      redirect:
        protocol: "{{ params.wordpress.ssl | ternary('https', 'http') }}"
        host: "{{ params.wordpress.domain }}"
        port: "{{ params.wordpress.ssl | ternary('443', '80') }}"
    - name: "wordpress"
      host: "{{ params.wordpress.domain }}"
      port: "{{ params.wordpress.ssl | ternary('443', '80') }}"
      ssl: "{{ params.wordpress.ssl }}"
      upstream:
        protocol: "http"
        port: "80"
      locations:
      - path: "/wp-admin/"
        includes:
        - "includes/file_upload.conf"
        - "includes/file_upload_ratelimit.conf"
      - path: "/"
    - name: "phpmyadmin"
      host: "{{ params.phpmyadmin.domain }}"
      port: "{{ params.phpmyadmin.port }}"
      ssl: "{{ params.phpmyadmin.ssl }}"
      upstream:
        protocol: "http"
        port: "80"
      locations:
      - path: "/"

- src: "nginx/includes/log.conf"
  params: 
    format: >-
      $remote_addr $sent_http_x_user_id $upstream_response_time $status
      $remote_user [$time_local] "$host" "$request"
      $body_bytes_sent "$http_referer" "$http_user_agent" $request_time

- src: "nginx/includes/limit_req_zone.conf"
  params: 
    zone: "mainlimit"
    size: "10m"
    rate: "2r/s"

- src: "nginx/includes/limit_conn_zone.conf"
  params:
    zone: "connlimit"
    size: "10m"

- src: "nginx/includes/limit_conn_zone.conf"
  dest: "nginx/includes/limit_conn_zone_file_upload.conf"
  params: 
    zone: "uploadconnlimit"
    size: "10m"

- src: "nginx/includes/proxy_cache.conf"
  params:
    proxy_cache_path: "/var/cache/nginx"
    levels: "1:2"
    keys_zone: "web_cache"
    size: "20m"
    max_size: "200m"
    inactive: "30m"

- src: "nginx/includes/timeouts.conf"
  params:
    proxy_connect_timeout: "30"
    proxy_send_timeout: "60"
    proxy_read_timeout: "60"
    send_timeout: "60"
    client_body_timeout: "5s"
    client_header_timeout: "5s"

- src: "nginx/includes/file_upload.conf"
  params: 
    proxy_read_timeout: "240"
    client_max_body_size: "10M"

- src: "nginx/includes/ratelimit.conf"
  dest: "nginx/includes/file_upload_ratelimit.conf"
  params:
    limit_req:
      zone: "mainlimit"
      burst: 6
      nodelay: true
    limit_conn:
      name: "uploadconnlimit"
      value: 5

#################
### Wordpress ###
#################

- src: "wordpress/Dockerfile"
  params:
    wordpress_image: "wordpress"
    wordpress_version: "5.2.2"

- src: "wordpress/wp-config.php"
  params: 
    db_password: "{{ params.wordpress.db_password }}"
    db_charset: "utf8mb4"
    db_collate: ""
    home: "{{ params.wordpress.ssl | ternary('https', 'http') }}://{{ params.wordpress.domain }}"
    siteurl: "{{ params.wordpress.ssl | ternary('https', 'http') }}://{{ params.wordpress.domain }}"
    auth_key: "{{ params.wordpress.config.auth_key }}"
    secure_auth_key: "{{ params.wordpress.config.secure_auth_key }}"
    logged_in_key: "{{ params.wordpress.config.logged_in_key }}"
    nonce_key: "{{ params.wordpress.config.nonce_key }}"
    auth_salt: "{{ params.wordpress.config.auth_salt }}"
    secure_auth_salt: "{{ params.wordpress.config.secure_auth_salt }}"
    logged_in_salt: "{{ params.wordpress.config.logged_in_salt }}"
    nonce_salt: "{{ params.wordpress.config.nonce_salt }}"
    table_prefix: "wp_"
    wplang: "en_US"
    wp_debug: "{{ params.wp_debug | default(false) | lower }}"

##################
### PHPMyAdmin ###
##################

- src: "phpmyadmin/Dockerfile"
  params:
    pma_image: "phpmyadmin/phpmyadmin"
    pma_version: "4.8.5"

- src: "phpmyadmin/config.user.inc.php"
  params:
    login_cookie_validity: 36000

#############
### MySQL ###
#############

- src: "mysql/Dockerfile"
  params:
    mysql_image: "mysql"
    mysql_version: "8.0.16"

- src: "mysql/mysqld.cnf"
  params:
    bind_address: "0.0.0.0"
    default_authentication_plugin: "mysql_native_password"
    collation_server: "utf8mb4_unicode_ci"
    character_set_server: "utf8mb4"
    slow_query_log: "1"
    slow_query_log_file: "var/log/mysql/mysql-slow.log"
    long_query_time: "3"
    log_error: "/var/log/mysql/error.log"
