templates:

- src: "compose/wordpress/app.env"
  dest: ".env"
  root: true
  params: 
    pod_repo: "{{ params.env.pod_repo }}"
    pod_repo_version: "{{ params.env.pod_repo_version }}"
    git_commit: "{{ params.env.git_commit }}"
    data_dir: "{{ params.env.data_dir }}"
    mysql_image: "{{ params.env.mysql_image }}"
    mysql_version: "{{ params.env.mysql_version }}"
    db_host: "{{ params.env.db_host }}"
    db_port: "{{ params.env.db_port }}"
    db_name: "{{ params.env.db_name }}"
    db_user: "{{ params.env.db_user }}"
    db_password: "{{ params.env.db_password }}"
    mysql_root_password: "{{ params.env.mysql_root_password }}"
    mysql_cmd: "{{ params.env.mysql_cmd }}"

- src: "compose/wordpress/app.docker-compose.yml"
  root: true  
  dest: "docker-compose.yml"

- src: "scripts/wordpress/compose.upgrade.app.sh"
  dest: "scripts/upgrade"
  mode: '0755'
  