templates:

- src: "compose/wordpress/.env"
  dest: ".env"
  root: true
  params: 
    pod_repo: "{{ params_aux.pod.repo }}"
    pod_repo_version: "{{ params_aux.pod.repo_version }}"
    git_commit: "{{ params_aux.git_commit }}"
    data_dir: "{{ params_aux.data_dir }}"
    mysql_image: "mysql"
    mysql_version: "8.0.16"
    db_host: "mysql"
    db_port: 3306
    db_name: "wordpress"
    db_user: "wp_user"
    db_password: "{{ params.db_password }}"
    mysql_root_password: "{{ params.mysql_root_password }}"
    mysql_cmd: "--default-authentication-plugin=mysql_native_password"
    wordpress_nginx_image: "{{ params.wordpress_nginx_image }}"
    wordpress_nginx_version: "{{ params.wordpress_nginx_version }}"
    wordpress_dev_repo_dir: "{{ params_aux.app.wordpress.dir_rel }}"

- src: "compose/wordpress/{{ params.docker_compose_file }}"
  root: true  
  dest: "docker-compose.yml"