templates:

- src: "compose/wordpress/dev.env"
  dest: ".env"
  root: true
  params: 
    pod_repo: "{{ params.env.pod_repo }}"
    pod_repo_version: "{{ params.env.pod_repo_version }}"
    git_commit: "{{ params.env.git_commit }}"
    data_dir: "{{ params.env.data_dir }}"
    mysql_image: "{{ params.env.mysql_image }}"
    mysql_version: "{{ params.env.mysql_version }}"
    db_host: "{{ params.env.db_host }}"
    db_port: "{{ params.env.db_port }}"
    db_name: "{{ params.env.db_name }}"
    db_user: "{{ params.env.db_user }}"
    db_password: "{{ params.env.db_password }}"
    mysql_root_password: "{{ params.env.mysql_root_password }}"
    mysql_cmd: "{{ params.env.mysql_cmd }}"
    wordpress_dev_repo_dir: "{{ params.env.wordpress_dev_repo_dir }}"

- src: "compose/wordpress/dev.docker-compose.yml"
  root: true  
  dest: "docker-compose.yml"

- src: "composer/Dockerfile"
  params:
    composer_image: "{{ params.composer.image }}"
    composer_version: "{{ params.composer.version }}"

- src: "scripts/compose/local.sh"
  dest: "run"
  root: true
  mode: '0755'
  params: 
    repo_name: "{{ params.run.repo_name }}"

- src: "scripts/wordpress/compose.env.local.sh"
  dest: "scripts/run"
  mode: '0755'
  params: 
    wordpress_dev_repo_dir: "{{ params.env_run.wordpress_dev_repo_dir }}"
    local_seed_data: "{{ params.env_run.local_seed_data }}"
    remote_seed_data: "{{ params.env_run.remote_seed_data }}"

- src: "scripts/wordpress/compose.setup.app.sh"
  dest: "scripts/setup"
  mode: '0755'
  params:
    url: "{{ params.setup.url }}"
    title: "{{ params.setup.title }}"
    admin_user: "{{ params.setup.admin_user }}"
    admin_password: "{{ params.setup.admin_password }}"
    admin_email: "{{ params.setup.admin_email }}"