templates:

- src: "compose/wordpress/dev.env"
  dest: ".env"
  root: true
  params: 
    pod_repo: "{{ params_aux.pod.repo }}"
    pod_repo_version: "{{ params_aux.pod.repo_version }}"
    git_commit: "{{ params_aux.git_commit }}"
    data_dir: "{{ params_aux.data_dir }}"
    mysql_image: "mysql"
    mysql_version: "8.0.16"
    db_host: "mysql"
    db_port: 3306
    db_name: "wordpress"
    db_user: "wp_user"
    db_password: "{{ params.env.db_password }}"
    mysql_root_password: "{{ params.env.mysql_root_password }}"
    mysql_cmd: "--default-authentication-plugin=mysql_native_password"
    wordpress_nginx_image: "{{ params.env.wordpress_nginx_image }}"
    wordpress_nginx_version: "{{ params.env.wordpress_nginx_version }}"
    wordpress_dev_repo_dir: "{{ params_aux.app.wordpress.dir_rel }}"

- src: "compose/wordpress/dev.docker-compose.yml"
  root: true  
  dest: "docker-compose.yml"

- src: "composer/Dockerfile"
  params:
    composer_image: "composer"
    composer_version: "1.8.6"

- src: "scripts/wordpress/dev.compose.run.sh"
  dest: "run"
  root: true
  mode: '0755'
  params: 
    repo_name: "{{ params_aux.repo_name }}"

- src: "scripts/wordpress/dev.compose.env.sh"
  dest: "scripts/run"
  mode: '0755'
  params: 
    wordpress_dev_repo_dir: "{{ params_aux.app.wordpress.dir_rel }}"

- src: "scripts/wordpress/app.compose.setup.sh"
  dest: "scripts/setup"
  mode: '0755'
  params:
    url: "{{ params.setup.url }}"
    title: "{{ params.setup.title }}"
    admin_user: "{{ params.setup.admin_user }}"
    admin_password: "{{ params.setup.admin_password }}"
    admin_email: "{{ params.setup.admin_email }}"