templates:

- src: "scripts/wordpress/run.sh"
  dest: "run"
  root: true
  mode: '0755'
  params: 
    repo_name: "{{ params_aux.repo_name }}"

- src: "composer/Dockerfile"
  params:
    composer_image: "composer"
    composer_version: "1.8.6"