version: '3.4'

networks:
  internet:
    driver: bridge
  local:
    driver: bridge
    internal: true
    
x-logging: 
  main: &mainlog
    options:
      max-size: 50m
      
services:
  proxy:
    build: 
      context: ./
      dockerfile: nginx/Dockerfile
      args:
        NGINX_VERSION: $NGINX_VERSION
    restart: on-failure
    depends_on:
    - main
    - db_admin
    ports:
    - "80:80"
    - "8080:8080"
    networks:
    - internet
    - local
    logging: *mainlog

  main:
    build: 
      context: ./
      dockerfile: wordpress/Dockerfile
      args:
        MAIN_IMAGE: $MAIN_IMAGE
        MAIN_VERSION: $MAIN_VERSION
    restart: on-failure
    depends_on:
    - db
    environment:
    - WORDPRESS_DB_HOST=$DB_HOST:$DB_PORT
    - WORDPRESS_DB_NAME=$DB_NAME
    - WORDPRESS_DB_USER=$DB_USER 
    networks:
    - internet
    - local
    logging: *mainlog

  db_admin:
    build: 
      context: ./
      dockerfile: phpmyadmin/Dockerfile
      args:
        PMA_VERSION: $PMA_VERSION
    restart: on-failure
    depends_on:
    - db
    environment:
    - PMA_HOST=$DB_HOST
    - PMA_PORT=$DB_PORT
    networks:
    - local
    logging: *mainlog

  db:
    build: 
      context: ./
      dockerfile: mysql/Dockerfile
      args:
        MYSQL_IMAGE: $MYSQL_IMAGE
        MYSQL_VERSION: $MYSQL_VERSION
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
    volumes:
    - /data/$PROJECT_NAME:/var/lib/mysql
    networks:
    - local
    logging: *mainlog
    command: --default-authentication-plugin=mysql_native_password
