templates:

- src: "compose/wordpress/app.env"
  dest: ".env"
  root: true
  params: 
    ctx_name: "{{ params.env.ctx_name }}"
    pod_repo: "{{ params.env.pod_repo }}"
    pod_repo_version: "{{ params.env.pod_repo_version }}"
    git_commit: "{{ params.env.git_commit }}"
    data_dir: "{{ params.env.data_dir }}"
    mysql_image: "{{ params.env.mysql_image }}"
    mysql_version: "{{ params.env.mysql_version }}"
    db_host: "{{ params.env.db_host }}"
    db_port: "{{ params.env.db_port }}"
    db_name: "{{ params.env.db_name }}"
    db_user: "{{ params.env.db_user }}"
    db_password: "{{ params.env.db_password }}"
    mysql_root_password: "{{ params.env.mysql_root_password }}"
    mysql_cmd: "{{ params.env.mysql_cmd }}"

- src: "compose/wordpress/app.docker-compose.yml"
  root: true  
  dest: "docker-compose.yml"

- src: "scripts/wordpress/compose.vars.local.sh"
  dest: "scripts/vars.sh"
  mode: '0755'
  params: 
    scripts_dir: "main/wordpress/files/scripts"
    script_run_file: "compose.sh"
    script_env_file: "compose.env.app.sh"
    repo_name: "{{ params.run.repo_name }}"
    setup_url: "{{ params.run.setup_url }}"
    setup_title: "{{ params.run.setup_title }}"
    setup_admin_user: "{{ params.run.setup_admin_user }}"
    setup_admin_password: "{{ params.run.setup_admin_password }}"
    setup_admin_email: "{{ params.run.setup_admin_email }}"
    setup_local_db_file: "{{ params.run.setup_local_db_file }}"
    setup_local_uploads_zip_file: "{{ params.run.setup_local_uploads_zip_file }}"
    setup_remote_db_file: "{{ params.run.setup_remote_db_file }}"
    setup_remote_uploads_zip_file: "{{ params.run.setup_remote_uploads_zip_file }}"
    setup_remote_bucket_path_db_file: "{{ params.run.setup_remote_bucket_path_db_file }}"
    setup_remote_bucket_path_uploads_file: "{{ params.run.setup_remote_bucket_path_uploads_file }}"
    setup_local_seed_data: "{{ params.run.setup_local_seed_data }}"
    setup_remote_seed_data: "{{ params.run.setup_remote_seed_data }}"
    s3_endpoint: "{{ params.run.s3_endpoint }}"
    use_aws_s3: "{{ params.run.use_aws_s3 }}"
    use_s3cmd: "{{ params.run.use_s3cmd }}"
    backup_bucket_name: "{{ params.run.backup_bucket_name }}"
    backup_bucket_path: "{{ params.run.backup_bucket_path }}"
    backup_delete_old_days: "{{ params.run.backup_delete_old_days }}"    
    db_user: "{{ params.env.db_user }}"
    db_pass: "{{ params.env.db_password }}"
    db_name: "{{ params.env.db_name }}"
    