params:

- name: "main/wordpress/vars/env.yml"
  params:
    env_files: {{ params.env_files | default([]) | to_json }}

- name: "main/wordpress/vars/main.app.yml"
  params:
    volumes:
      data_dir: "{{ params_aux.data_dir_inside }}"
    wordpress:
      env: "{{ params.wordpress.env }}"
      domain: "{{ params.wordpress.domain }}"
      db_password: "{{ credentials.wordpress.db_password }}"
      ssl: "{{ params.wordpress.ssl }}"
      config:
        auth_key: "{{ credentials.wordpress.config.auth_key }}"
        secure_auth_key: "{{ credentials.wordpress.config.secure_auth_key }}"
        logged_in_key: "{{ credentials.wordpress.config.logged_in_key }}"
        nonce_key: "{{ credentials.wordpress.config.nonce_key }}"
        auth_salt: "{{ credentials.wordpress.config.auth_salt }}"
        secure_auth_salt: "{{ credentials.wordpress.config.secure_auth_salt }}"
        logged_in_salt: "{{ credentials.wordpress.config.logged_in_salt }}"
        nonce_salt: "{{ credentials.wordpress.config.nonce_salt }}"
    phpmyadmin:
      domain: "{{ params.phpmyadmin.domain }}"
      port: "{{ params.phpmyadmin.port }}"
      ssl: "{{ params.phpmyadmin.ssl }}"
    mysql: 
      root_password: "{{ credentials.mysql.root_password }}"
    toolbox:
      s3_endpoint: "{{ params.toolbox.s3_endpoint | default('') }}"
      bucket:
        access_key: "{{ credentials.bucket.access_key | default('') }}"
        secret_key: "{{ credentials.bucket.secret_key | default('') }}"

- name: "main/wordpress/vars/compose.local.yml"
  params: 
    env:  
      db_password: "{{ credentials.wordpress.db_password }}"
      mysql_root_password: "{{ credentials.mysql.root_password }}"
      ctx_name: "{{ params_aux.pod_id }}"
      pod_repo: "{{ params_aux.pod.repo }}"
      pod_repo_version: "{{ params_aux.pod.repo_version }}"
      git_commit: "{{ params_aux.git_commit }}"
      pod_env_dir: "{{ params_aux.pod_env_dir }}"
      data_dir: "{{ params_aux.data_dir }}"
      wordpress_dev_repo_dir: "{{ params_aux.app.wordpress.dir_rel }}"
      db_host: "{{ params.mysql.db_host | default('mysql', true) }}"
      db_port: "{{ params.mysql.db_port | default('3306', true) }}"
      db_name: "{{ params.mysql.db_name | default('wordpress', true) }}"
      db_user: "{{ params.mysql.db_user | default('wp_user', true) }}"
      mysql_cmd: "{{ params.mysql.cmd | default('') }}"  
      nginx_image: "{{ params.nginx.image | default('nginx') }}"
      nginx_version: "{{ params.nginx.version | default('1.14.2-alpine') }}"
      wordpress_image: "{{ params.wordpress.image }}"
      wordpress_version: "{{ params.wordpress.version }}"
      wordpress_env: "{{ params.wordpress.env }}"
      pma_image: "{{ params.pma.image | default('phpmyadmin/phpmyadmin') }}"
      pma_version: "{{ params.pma.version | default('4.8.5') }}"
      mysql_image: "{{ params.mysql.image }}"
      mysql_version: "{{ params.mysql.version }}"
      toolbox_image: "{{ params.toolbox.image }}"
      toolbox_version: "{{ params.toolbox.version }}"
      composer_image: "{{ params.composer.image }}"
      composer_version: "{{ params.composer.version }}"
    run:
      repo_name: "{{ params_aux.repo_name }}"
      pod_env_dir: "{{ params_aux.pod_env_dir }}"
      setup_url: "{{ params.setup.url }}"
      setup_title: "{{ params.setup.title }}"
      setup_admin_user: "{{ credentials.wordpress.setup.admin_user }}"
      setup_admin_password: "{{ credentials.wordpress.setup.admin_password }}"
      setup_admin_email: "{{ credentials.wordpress.setup.admin_email }}"
      setup_local_db_file: "{{ params.run.local_db_file | default('') }}"
      setup_local_uploads_zip_file: "{{ params.run.local_uploads_zip_file | default('') }}"
      setup_remote_db_file: "{{ params.run.remote_db_file | default('') }}"
      setup_remote_uploads_zip_file: "{{ params.run.remote_uploads_zip_file | default('') }}"
      setup_remote_bucket_path_db_dir: "{{ params.run.remote_bucket_path_db_dir | default('') }}"
      setup_remote_bucket_path_uploads_dir: "{{ params.run.remote_bucket_path_uploads_dir | default('') }}"
      setup_remote_bucket_path_db_file: "{{ params.run.remote_bucket_path_db_file | default('') }}"
      setup_remote_bucket_path_uploads_file: "{{ params.run.remote_bucket_path_uploads_file | default('') }}"
      setup_local_seed_data: "{{ params.run.local_seed_data | default('') }}"
      setup_remote_seed_data: "{{ params.run.remote_seed_data | default('') }}"
      s3_endpoint: "{{ params.toolbox.s3_endpoint | default('') }}"
      use_aws_s3: "{{ params.toolbox.use_aws_s3_cli | default(false) }}"
      use_s3cmd: "{{ params.toolbox.use_s3cmd | default(false) }}"
      backup_bucket_name: "{{ params.run.backup_bucket_name | default('') }}"
      backup_bucket_path: "{{ params.run.backup_bucket_path | default('') }}"
      backup_bucket_db_sync_dir: "{{ params.run.backup_bucket_db_sync_dir | default('') }}"
      backup_bucket_uploads_sync_dir: "{{ params.run.backup_bucket_uploads_sync_dir | default('') }}"
      backup_delete_old_days: "{{ params.run.backup_delete_old_days }}"
      old_domain_host: "{{ params.run.old_domain_host | default('') }}"
      new_domain_host: "{{ params.run.new_domain_host | default('') }}"
    env_run:
      wordpress_dev_repo_dir: "{{ params_aux.app.wordpress.dir_rel }}"